services:
  loggerr:
    build: .
    container_name: loggerr
    ports:
      - "3000:3000"
      - "9090:9090"
    environment:
      PORT: 3000
      DATA_DIR: /app/data
      MEDIA_DIR: /app/media
      TZ: Europe/Amsterdam
      TCP_TRIGGER_PORT: 9090
    volumes:
      - ./data:/app/data
      - ./media:/app/media
    restart: unless-stopped
