import { useEffect, useMemo, useState } from 'react';
import { Activity, Bell, CalendarDays, Check, Circle, Database, Download, HardDrive, Pencil, Plus, Radio, Settings, Square, Trash2, X } from 'lucide-react';
import { api } from './api.js';
import AudioPlayer from './AudioPlayer.jsx';

const emptyRecording = { title: '', enabled: true, sourceType: 'stream', sourceUrl: '', ingestPort: 9100, triggerMode: 'continuous', schedule: { type: 'continuous', days: [0,1,2,3,4,5,6], startTime: '00:00', endTime: '23:59' }, chunkMinutes: 60, mode: 'copy', sourceExtension: 'aac', presetId: 'mp3-128', prefix: '', streamName: '', dateFormat: 'YYYY-MM-DD', folder: '', retention: { value: 1, unit: 'months' }, monitoring: { enabled: true, silenceThresholdDb: -50, silenceDurationSeconds: 10, signalLossSeconds: 10, alertsEnabled: true } };
const days = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
function Field({ label, children, wide = false }) { return <label className={wide ? 'field wide' : 'field'}><span>{label}</span>{children}</label>; }
function meterWidth(db) { const value = Number(db); return `${Math.max(0, Math.min(100, ((Number.isFinite(value) ? value : -100) + 60) / 60 * 100))}%`; }
function StereoMeter({ audio }) {
  if (!audio) return <div className="audio-meter inactive"><span>MONITOR OFF</span></div>;
  return <div className={`audio-monitor ${audio.silent ? 'silent' : ''}`}><div className="meter-head"><span>{audio.silent ? `SILENCE ${Math.floor(audio.silenceSeconds)}s` : 'LIVE AUDIO'}</span><strong>{audio.channels[0]?.rmsDb?.toFixed(1) ?? '—'} dBFS</strong></div>{['L','R'].map((label, index) => <div className="meter-row" key={label}><b>{label}</b><div className="meter-track"><i style={{ width: meterWidth(audio.channels[index]?.peakDb) }}/><em style={{ left: meterWidth(audio.channels[index]?.rmsDb) }}/></div></div>)}</div>;
}

function RecordingForm({ value, presets, onSave, onClose }) {
  const [form, setForm] = useState(() => structuredClone({ ...emptyRecording, ...value, monitoring: { ...emptyRecording.monitoring, ...value?.monitoring } }));
  const patch = update => setForm(current => ({ ...current, ...update }));
  const patchSchedule = update => patch({ schedule: { ...form.schedule, ...update } });
  const toggleDay = day => patchSchedule({ days: form.schedule.days.includes(day) ? form.schedule.days.filter(item => item !== day) : [...form.schedule.days, day] });
  return <div className="modal-backdrop"><form className="modal" onSubmit={event => { event.preventDefault(); onSave(form); }}><header><div><p className="eyebrow">RECORDING CONFIGURATION</p><h2>{value ? 'Edit recording' : 'New recording'}</h2></div><button type="button" className="icon" onClick={onClose}><X/></button></header><div className="form-grid">
    <Field label="Title" wide><input required value={form.title} onChange={e => patch({ title: e.target.value })} placeholder="Qmusic"/></Field>
    <Field label="Source type"><select value={form.sourceType} onChange={e => patch({ sourceType: e.target.value, mode: e.target.value === 'ingest' ? 'transcode' : form.mode })}><option value="stream">Online stream</option><option value="ingest">Audio ingest</option></select></Field>
    {form.sourceType === 'stream' ? <Field label="Stream URL" wide><input required type="url" value={form.sourceUrl} onChange={e => patch({ sourceUrl: e.target.value })} placeholder="https://…/live.aac"/></Field> : <Field label="Ingest port"><input type="number" min="1024" max="65535" value={form.ingestPort} onChange={e => patch({ ingestPort: Number(e.target.value) })}/></Field>}
    <Field label="Control"><select value={form.triggerMode} onChange={e => patch({ triggerMode: e.target.value })}><option value="continuous">Follow schedule</option><option value="trigger">REST / TCP trigger</option></select></Field>
    <Field label="Schedule"><select value={form.schedule.type} disabled={form.triggerMode === 'trigger'} onChange={e => patchSchedule({ type: e.target.value })}><option value="continuous">24 / 7</option><option value="weekly">Weekly schedule</option><option value="once">Once</option></select></Field>
    {form.triggerMode !== 'trigger' && form.schedule.type === 'weekly' && <div className="wide schedule"><div className="days">{days.map((name, day) => <button type="button" className={form.schedule.days.includes(day) ? 'day active' : 'day'} key={name} onClick={() => toggleDay(day)}>{name}</button>)}</div><Field label="Start"><input type="time" value={form.schedule.startTime} onChange={e => patchSchedule({ startTime: e.target.value })}/></Field><Field label="End"><input type="time" value={form.schedule.endTime} onChange={e => patchSchedule({ endTime: e.target.value })}/></Field></div>}
    {form.triggerMode !== 'trigger' && form.schedule.type === 'once' && <><Field label="Starts"><input type="datetime-local" value={form.schedule.startAt || ''} onChange={e => patchSchedule({ startAt: e.target.value })}/></Field><Field label="Ends"><input type="datetime-local" value={form.schedule.endAt || ''} onChange={e => patchSchedule({ endAt: e.target.value })}/></Field></>}
    <Field label="Chunk length"><select value={form.chunkMinutes} onChange={e => patch({ chunkMinutes: Number(e.target.value) })}>{[5,15,30,60,120].map(value => <option key={value} value={value}>{value < 60 ? `${value} minutes` : `${value / 60} hour${value > 60 ? 's' : ''}`}</option>)}</select></Field>
    <Field label="Encoding"><select disabled={form.sourceType === 'ingest'} value={form.mode} onChange={e => patch({ mode: e.target.value })}><option value="copy">Same as source</option><option value="transcode">Transcode preset</option></select></Field>
    {form.mode === 'copy' ? <Field label="Source extension"><select value={form.sourceExtension} onChange={e => patch({ sourceExtension: e.target.value })}><option>aac</option><option>mp3</option><option>ogg</option><option>opus</option></select></Field> : <Field label="Preset"><select value={form.presetId} onChange={e => patch({ presetId: e.target.value })}>{presets.map(preset => <option key={preset.id} value={preset.id}>{preset.name}</option>)}</select></Field>}
    <Field label="Filename prefix"><input value={form.prefix} onChange={e => patch({ prefix: e.target.value })} placeholder="Uses title when empty"/></Field><Field label="Stream name"><input value={form.streamName} onChange={e => patch({ streamName: e.target.value })} placeholder="5500 / DAB / DHD"/></Field>
    <Field label="Date format"><select value={form.dateFormat} onChange={e => patch({ dateFormat: e.target.value })}><option>YYYY-MM-DD</option><option>YYYYMMDD</option><option>DDMMYY</option></select></Field><Field label="Media folder"><input value={form.folder} onChange={e => patch({ folder: e.target.value })} placeholder="Defaults to normalized title"/></Field>
    <Field label="Audio monitoring"><label className="switch"><input type="checkbox" checked={form.monitoring.enabled} onChange={e => patch({ monitoring: { ...form.monitoring, enabled: e.target.checked } })}/><span>Live stereo and silence meter</span></label></Field><Field label="Silence detection"><div className="inline"><input type="number" min="-100" max="-1" disabled={!form.monitoring.enabled} value={form.monitoring.silenceThresholdDb} onChange={e => patch({ monitoring: { ...form.monitoring, silenceThresholdDb: Number(e.target.value) } })}/><span className="input-unit">dBFS for</span><input type="number" min="1" max="3600" disabled={!form.monitoring.enabled} value={form.monitoring.silenceDurationSeconds} onChange={e => patch({ monitoring: { ...form.monitoring, silenceDurationSeconds: Number(e.target.value) } })}/><span className="input-unit">sec</span></div></Field><Field label="Operational alerts"><label className="switch"><input type="checkbox" checked={form.monitoring.alertsEnabled} onChange={e => patch({ monitoring: { ...form.monitoring, alertsEnabled: e.target.checked } })}/><span>Silence, signal loss and failures</span></label></Field><Field label="Signal-loss delay"><div className="inline"><input type="number" min="2" max="3600" disabled={!form.monitoring.enabled || !form.monitoring.alertsEnabled} value={form.monitoring.signalLossSeconds} onChange={e => patch({ monitoring: { ...form.monitoring, signalLossSeconds: Number(e.target.value) } })}/><span className="input-unit">seconds</span></div></Field>
    <Field label="Retention"><div className="inline"><input type="number" min="1" disabled={form.retention.unit === 'forever'} value={form.retention.value} onChange={e => patch({ retention: { ...form.retention, value: Number(e.target.value) } })}/><select value={form.retention.unit} onChange={e => patch({ retention: { ...form.retention, unit: e.target.value } })}><option value="days">Days</option><option value="months">Months</option><option value="years">Years</option><option value="forever">Keep forever</option></select></div></Field><Field label="Enabled"><label className="switch"><input type="checkbox" checked={form.enabled} onChange={e => patch({ enabled: e.target.checked })}/><span>Start when saved</span></label></Field>
  </div><footer><button type="button" onClick={onClose}>Cancel</button><button className="primary" type="submit">Save recording</button></footer></form></div>;
}

function formatBytes(bytes = 0) { if (!bytes) return '0 B'; const units = ['B','KB','MB','GB','TB']; const index = Math.min(units.length - 1, Math.floor(Math.log(bytes) / Math.log(1024))); return `${(bytes / 1024 ** index).toFixed(index > 1 ? 1 : 0)} ${units[index]}`; }
function OperationsPage({ alerts, storage, recordings, reload }) {
  return <section><div className="page-title"><div><p className="eyebrow">SYSTEM HEALTH</p><h1>Operations</h1><p>Recorder alerts and archive storage usage.</p></div><button onClick={async () => { await api.acknowledgeAllAlerts(); reload(); }}><Check/> Acknowledge all</button></div><div className="stats"><div><Bell/><span><strong>{alerts.filter(alert => alert.active).length}</strong>Active alerts</span></div><div><HardDrive/><span><strong>{formatBytes(storage?.audioBytes)}</strong>Audio</span></div><div><Activity/><span><strong>{formatBytes(storage?.waveformBytes)}</strong>Waveforms</span></div></div><div className="operations-grid"><div className="panel"><h3>Alerts</h3><div className="alert-list">{alerts.length === 0 && <div className="empty small">No alerts recorded.</div>}{alerts.map(alert => <article className={`alert-item ${alert.active ? 'active' : ''} ${alert.severity}`} key={alert.id}><div><span>{alert.type.replace('-', ' ')}</span><strong>{alert.recordingTitle}</strong><p>{alert.message}</p><small>{new Date(alert.createdAt).toLocaleString()}{alert.resolvedAt ? ` · recovered ${new Date(alert.resolvedAt).toLocaleString()}` : ''}</small></div>{!alert.acknowledgedAt && <button className="icon" onClick={async () => { await api.acknowledgeAlert(alert.id); reload(); }}><Check/></button>}</article>)}</div></div><div className="panel"><h3>Storage by recording</h3>{recordings.map(recording => { const usage = storage?.recordings?.[recording.id]; return <div className="storage-row" key={recording.id}><div><strong>{recording.title}</strong><small>{usage?.fileCount || 0} audio files</small></div><span>{formatBytes(usage?.totalBytes)}</span></div>; })}<div className="storage-total"><strong>Total archive</strong><span>{formatBytes(storage?.totalBytes)}</span></div></div></div></section>;
}

function SettingsPage({ presets, reload }) {
  const [draft, setDraft] = useState({ name: '', extension: 'mp3', args: '-c:a libmp3lame -b:a 128k -ar 44100' });
  return <section><div className="page-title"><div><p className="eyebrow">ENCODING</p><h1>Transcode presets</h1><p>Manage the FFmpeg formats available to recordings and ingest feeds.</p></div></div><div className="settings-grid"><div className="panel"><h3>Available presets</h3>{presets.map(preset => <div className="preset" key={preset.id}><div><strong>{preset.name}</strong><code>{preset.args.join(' ')}</code></div><button className="icon danger" onClick={async () => { await api.deletePreset(preset.id); reload(); }}><Trash2/></button></div>)}</div><form className="panel" onSubmit={async e => { e.preventDefault(); await api.createPreset({ ...draft, args: draft.args.match(/(?:[^\s"]+|"[^"]*")+/g) || [] }); setDraft({ name: '', extension: 'mp3', args: '' }); reload(); }}><h3>Add preset</h3><Field label="Name"><input required value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })}/></Field><Field label="Extension"><input required value={draft.extension} onChange={e => setDraft({ ...draft, extension: e.target.value })}/></Field><Field label="FFmpeg arguments"><input required value={draft.args} onChange={e => setDraft({ ...draft, args: e.target.value })}/></Field><button className="primary">Add preset</button></form></div></section>;
}

export default function App() {
  const [recordings, setRecordings] = useState([]); const [presets, setPresets] = useState([]); const [editing, setEditing] = useState(undefined); const [page, setPage] = useState('recordings'); const [selected, setSelected] = useState(null); const [files, setFiles] = useState([]); const [file, setFile] = useState(null); const [date, setDate] = useState(new Date().toISOString().slice(0,10)); const [alerts, setAlerts] = useState([]); const [storage, setStorage] = useState(null); const [error, setError] = useState('');
  const reload = async () => { try { const [items, codecs] = await Promise.all([api.recordings(), api.presets()]); setRecordings(items); setPresets(codecs); } catch (e) { setError(e.message); } };
  const reloadOperations = async () => { try { const [items, usage] = await Promise.all([api.alerts(), api.storage()]); setAlerts(items); setStorage(usage); } catch (e) { setError(e.message); } };
  useEffect(() => { reload(); reloadOperations(); const operationsTimer = setInterval(reloadOperations, 10_000); const events = new EventSource('/api/events'); events.onmessage = event => setRecordings(JSON.parse(event.data)); return () => { clearInterval(operationsTimer); events.close(); }; }, []);
  useEffect(() => { if (!selected) return; api.files(selected.id).then(items => { setFiles(items); setDate(current => items.length && !items.some(item => item.date === current) ? items[0].date : current); }).catch(e => setError(e.message)); }, [selected]);
  const visibleFiles = useMemo(() => files.filter(item => item.date === date), [files, date]);
  const saveRecording = async form => { try { editing ? await api.updateRecording(editing.id, form) : await api.createRecording(form); setEditing(undefined); reload(); } catch (e) { setError(e.message); } };
  return <div className="shell"><aside><div className="brand"><div className="brand-mark"><Activity/></div><div><strong>LOGGERR</strong><small>Broadcast archive</small></div></div><nav><button className={page === 'recordings' ? 'active' : ''} onClick={() => setPage('recordings')}><Radio/>Recordings</button><button className={page === 'playback' ? 'active' : ''} onClick={() => setPage('playback')}><CalendarDays/>Playback</button><button className={page === 'operations' ? 'active' : ''} onClick={() => { setPage('operations'); reloadOperations(); }}><Bell/>Operations{alerts.some(alert => alert.active && !alert.acknowledgedAt) && <i className="nav-alert"/>}</button><button className={page === 'settings' ? 'active' : ''} onClick={() => setPage('settings')}><Settings/>Options</button></nav><div className="system"><span><Circle/> Recorder service</span><strong>ONLINE</strong></div></aside><main>{error && <div className="error" onClick={() => setError('')}>{error}</div>}
    {page === 'recordings' && <section><div className="page-title"><div><p className="eyebrow">CAPTURE OVERVIEW</p><h1>Recordings</h1><p>Continuous, scheduled and externally triggered audio logging.</p></div><button className="primary" onClick={() => setEditing(null)}><Plus/> New recording</button></div><div className="stats"><div><Radio/><span><strong>{recordings.filter(r => r.status.state === 'recording').length}</strong>Active</span></div><div><Database/><span><strong>{recordings.length}</strong>Configured</span></div><div><HardDrive/><span><strong>{recordings.filter(r => r.enabled).length}</strong>Enabled</span></div></div><div className="recording-list">{recordings.length === 0 && <div className="empty">No recordings configured. Add your first radio stream.</div>}{recordings.map(recording => <article key={recording.id}><div className={`status-dot ${recording.status.state}`}/><div className="recording-main"><div><h3>{recording.title}</h3><p>{recording.sourceType === 'stream' ? recording.sourceUrl : `Ingest on port ${recording.ingestPort}`}</p></div><div className="filename"><span>CURRENT FILE</span><code>{recording.status.currentFile || recording.status.error || 'Waiting for audio…'}</code></div></div><StereoMeter audio={recording.status.audio}/><div className="meta"><span>{recording.chunkMinutes} min chunks</span><span>{recording.mode === 'copy' ? 'Source codec' : presets.find(p => p.id === recording.presetId)?.name}</span><span className={`badge ${recording.status.state}`}>{recording.status.state}</span></div><div className="actions">{recording.triggerMode === 'trigger' && <button className="icon" title="Trigger" onClick={async () => { await api.trigger(recording.id, recording.triggered ? 'stop' : 'start'); reload(); }}>{recording.triggered ? <Square/> : <Radio/>}</button>}<button className="icon" onClick={() => { setEditing(recording); }}><Pencil/></button><button className="icon danger" onClick={async () => { if (confirm(`Delete ${recording.title}? Recorded files are kept.`)) { await api.deleteRecording(recording.id); reload(); } }}><Trash2/></button></div></article>)}</div></section>}
    {page === 'playback' && <section><div className="page-title"><div><p className="eyebrow">ARCHIVE</p><h1>Playback</h1><p>Browse, audition and download logged audio by date.</p></div></div><div className="playback-layout"><div className="panel browser"><Field label="Recording"><select value={selected?.id || ''} onChange={e => { const recording = recordings.find(item => item.id === e.target.value); setSelected(recording); setFile(null); }}><option value="">Select recording…</option>{recordings.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></Field><Field label="Date"><input type="date" value={date} onChange={e => setDate(e.target.value)}/></Field><div className="files">{visibleFiles.map(item => <button className={file?.name === item.name ? 'file active' : 'file'} key={item.name} onClick={() => setFile(item)}><span><strong>{item.name}</strong><small>{(item.size / 1048576).toFixed(1)} MB</small></span><a href={item.url} download onClick={e => e.stopPropagation()}><Download/></a></button>)}{selected && visibleFiles.length === 0 && <div className="empty small">No files for this date.</div>}</div></div><AudioPlayer file={file}/></div></section>}
    {page === 'operations' && <OperationsPage alerts={alerts} storage={storage} recordings={recordings} reload={reloadOperations}/>}
    {page === 'settings' && <SettingsPage presets={presets} reload={reload}/>}</main>{editing !== undefined && <RecordingForm value={editing} presets={presets} onSave={saveRecording} onClose={() => setEditing(undefined)}/>}</div>;
}
