using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Runtime.InteropServices;
using System.Threading.Channels;

namespace Loggerr.Ingest;

public sealed class CaptureSession : IAsyncDisposable {
  private readonly Uri server; private readonly string token; private readonly IngestFeed feed; private readonly AudioDevice device; private readonly EncodingProfile encoding; private readonly Action<double, double, string> feedback; private readonly CancellationTokenSource cancellation = new(); private readonly PortAudio.StreamCallback callback; private readonly LocalEncoder encoder; private IntPtr stream; private Task? sender; private long lastMeterTick;
  public CaptureSession(Uri server, string token, IngestFeed feed, AudioDevice device, EncodingProfile encoding, Action<double, double, string> feedback) { this.server = server; this.token = token; this.feed = feed; this.device = device; this.encoding = encoding; this.feedback = feedback; encoder = new LocalEncoder(encoding, feed.Format); callback = AudioCallback; }
  public Task StartAsync() { if (device.MaxInputChannels < feed.Format.Channels) throw new InvalidOperationException($"Device has {device.MaxInputChannels} inputs; feed requires {feed.Format.Channels}"); var channels = feed.Format.Channels; var parameters = new PortAudio.StreamParameters { Device = device.Index, ChannelCount = channels, SampleFormat = PortAudio.Float32, SuggestedLatency = PortAudio.GetLowInputLatency(device.Index) }; encoder.Start(); PortAudio.Check(PortAudio.Pa_OpenStream(out stream, ref parameters, IntPtr.Zero, feed.Format.SampleRate, 0, 0, callback, IntPtr.Zero)); PortAudio.Check(PortAudio.Pa_StartStream(stream)); sender = SendLoopAsync(cancellation.Token); feedback(-100, -100, $"Capturing via {device.HostApi}"); return Task.CompletedTask; }
  private int AudioCallback(IntPtr input, IntPtr _output, uint frameCount, IntPtr _timeInfo, uint _flags, IntPtr _userData) { if (input == IntPtr.Zero) return 0; var channels = feed.Format.Channels; var samples = new float[checked((int)frameCount * channels)]; Marshal.Copy(input, samples, 0, samples.Length); var bytes = new byte[samples.Length * sizeof(float)]; Buffer.BlockCopy(samples, 0, bytes, 0, bytes.Length); encoder.Input.TryWrite(bytes); var tick = Environment.TickCount64; if (tick - lastMeterTick >= 100) { lastMeterTick = tick; var left = Level(samples, channels, 0); var right = channels > 1 ? Level(samples, channels, 1) : left; feedback(left, right, ""); } return 0; }
  private static double Level(float[] samples, int channels, int channel) { double sum = 0; var count = 0; for (var index = channel; index < samples.Length; index += channels) { sum += samples[index] * samples[index]; count++; } return count == 0 ? -100 : Math.Max(-100, 20 * Math.Log10(Math.Sqrt(sum / count) + 1e-10)); }
  private async Task SendLoopAsync(CancellationToken cancel) { using var client = new HttpClient { BaseAddress = server, Timeout = Timeout.InfiniteTimeSpan }; client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token); while (!cancel.IsCancellationRequested) { try { feedback(-100, -100, "Connecting"); using var content = new ChannelContent(encoder.Output, encoder.Codec, encoder.Bitrate, feed.Format, cancel); feedback(-100, -100, $"Streaming {encoding.DisplayName}"); using var response = await client.PutAsync(feed.Endpoint, content, cancel); if (response.StatusCode is HttpStatusCode.Unauthorized or HttpStatusCode.Forbidden) { feedback(-100, -100, "Authentication failed"); return; } if (!response.IsSuccessStatusCode) { feedback(-100, -100, $"Server: {(int)response.StatusCode}"); await Task.Delay(2000, cancel); } } catch (OperationCanceledException) when (cancel.IsCancellationRequested) { break; } catch (Exception error) { feedback(-100, -100, $"Reconnect: {error.Message}"); try { await Task.Delay(2000, cancel); } catch (OperationCanceledException) { break; } } } }
  public async ValueTask DisposeAsync() { cancellation.Cancel(); if (stream != IntPtr.Zero) { PortAudio.Pa_StopStream(stream); PortAudio.Pa_CloseStream(stream); stream = IntPtr.Zero; } await encoder.DisposeAsync(); if (sender is not null) try { await sender; } catch (OperationCanceledException) {} cancellation.Dispose(); }
}

internal sealed class ChannelContent : HttpContent {
  private readonly ChannelReader<byte[]> reader; private readonly CancellationToken cancellation;
  public ChannelContent(ChannelReader<byte[]> reader, string codec, int bitrate, AudioFormat format, CancellationToken cancellation) { this.reader = reader; this.cancellation = cancellation; Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream"); Headers.Add("X-Loggerr-Codec", codec); Headers.Add("X-Loggerr-Sample-Rate", format.SampleRate.ToString()); Headers.Add("X-Loggerr-Channels", format.Channels.ToString()); if (bitrate > 0) Headers.Add("X-Loggerr-Bitrate", bitrate.ToString()); }
  protected override async Task SerializeToStreamAsync(Stream stream, TransportContext? context) { await foreach (var buffer in reader.ReadAllAsync(cancellation)) { await stream.WriteAsync(buffer, cancellation); await stream.FlushAsync(cancellation); } }
  protected override bool TryComputeLength(out long length) { length = 0; return false; }
}
